// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpiwcnmimoxiqjddliok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwaXdjbm1pbW94aXFqZGRsaW9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NjE5ODgsImV4cCI6MjA1OTEzNzk4OH0.wpIJb9poWByyWY6Zw8Fptc53vNDlpd_kF8vVt76yBpY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);